// Wails runtime - these will be generated by wails generate module
// For development, we provide type definitions

export interface ScanProgress {
  totalFiles: number
  scannedFiles: number
  foundFiles: number
  isScanning: boolean
}

export interface FileInfo {
  path: string
  size: number
  architecture: string
  isSigned: boolean
  signerInfo: string
  importedDLLs: ImportInfo[]
  importCount: number
}

export interface ImportInfo {
  dllName: string
  functions: string[]
}

export interface ScanConfig {
  directory: string
  minSize: number
  maxSize: number
  architecture: string
  extensions: string[]
  workers: number
  signFilter: string
  showImports: boolean
}

export interface InjectConfig {
  pePath: string
  shellcodePath: string
  method: string
  preserveSig: boolean
  funcName: string
  backup: boolean
}

export interface InjectResult {
  success: boolean
  message: string
  outputPath: string
  originalSize: number
  modifiedSize: number
}

export interface PEInfo {
  path: string
  size: number
  architecture: string
  isSigned: boolean
  signerInfo: string
  importedDLLs: ImportDLLInfo[]
  importCount: number
  hasTLS: boolean
  isDll: boolean
  entryPoint: number
  imageBase: number
  numberOfSections: number
  hasExport: boolean
}

export interface ImportDLLInfo {
  dllName: string
  functions: string[]
}

export interface TemplateInfo {
  name: string
  path: string
  size: number
  description: string
}

// App bindings - these will be replaced by wailsjs bindings
declare global {
  interface Window {
    go?: {
      main?: {
        App?: {
          SelectDirectory: () => Promise<string>
          SelectFile: (title: string, filter: string) => Promise<string>
          SelectPEFile: () => Promise<string>
          SelectShellcodeFile: () => Promise<string>
          StartScan: (config: ScanConfig) => Promise<void>
          StopScan: () => Promise<void>
          GetScanProgress: () => Promise<ScanProgress>
          GetScanResults: () => Promise<FileInfo[]>
          GetPEInfo: (path: string) => Promise<PEInfo>
          Inject: (config: InjectConfig) => Promise<InjectResult>
          GetDefaultConfig: () => Promise<{
            defaultScanDir: string
            defaultMinSize: number
            defaultMaxSize: number
            defaultArch: string
            defaultSignFilter: string
            defaultWorkers: number
          }>
          GetTemplates: () => Promise<TemplateInfo[]>
        }
      }
    }
    runtime?: {
      EventsEmit: (eventName: string, data?: unknown) => void
      EventsOn: (eventName: string, callback: (data?: unknown) => void) => void
      EventsOff: (eventName: string) => void
      WindowMinimise: () => void
      WindowToggleMaximise: () => void
      WindowClose: () => void
      WindowStartDrag: () => void
    }
  }
}

export const SelectDirectory = async (): Promise<string> => {
  if (window.go?.main?.App?.SelectDirectory) {
    return await window.go.main.App.SelectDirectory()
  }
  // Fallback for web development
  return prompt('Enter directory path:') || ''
}

export const SelectPEFile = async (): Promise<string> => {
  if (window.go?.main?.App?.SelectPEFile) {
    return await window.go.main.App.SelectPEFile()
  }
  return prompt('Enter PE file path:') || ''
}

export const SelectShellcodeFile = async (): Promise<string> => {
  if (window.go?.main?.App?.SelectShellcodeFile) {
    return await window.go.main.App.SelectShellcodeFile()
  }
  return prompt('Enter shellcode file path:') || ''
}

export const StartScan = async (config: ScanConfig): Promise<void> => {
  if (window.go?.main?.App?.StartScan) {
    return await window.go.main.App.StartScan(config)
  }
  console.log('StartScan called with:', config)
}

export const StopScan = async (): Promise<void> => {
  if (window.go?.main?.App?.StopScan) {
    return await window.go.main.App.StopScan()
  }
  console.log('StopScan called')
}

export const GetScanResults = async (): Promise<FileInfo[]> => {
  if (window.go?.main?.App?.GetScanResults) {
    return await window.go.main.App.GetScanResults()
  }
  return []
}

export const GetPEInfo = async (path: string): Promise<PEInfo> => {
  if (window.go?.main?.App?.GetPEInfo) {
    return await window.go.main.App.GetPEInfo(path)
  }
  throw new Error('GetPEInfo not available')
}

export const Inject = async (config: InjectConfig): Promise<InjectResult> => {
  if (window.go?.main?.App?.Inject) {
    return await window.go.main.App.Inject(config)
  }
  throw new Error('Inject not available')
}

export const GetDefaultConfig = async () => {
  if (window.go?.main?.App?.GetDefaultConfig) {
    return await window.go.main.App.GetDefaultConfig()
  }
  return {
    defaultScanDir: 'C:\\Program Files\\',
    defaultMinSize: 0,
    defaultMaxSize: 61440,
    defaultArch: 'x64',
    defaultSignFilter: 'signed',
    defaultWorkers: 4,
  }
}

export const EventsOn = (eventName: string, callback: (data?: unknown) => void) => {
  if (window.runtime?.EventsOn) {
    window.runtime.EventsOn(eventName, callback)
  } else {
    console.log(`EventsOn: ${eventName} (not available in web mode)`)
  }
}

export const EventsOff = (eventName: string) => {
  if (window.runtime?.EventsOff) {
    window.runtime.EventsOff(eventName)
  }
}

export const GetTemplates = async (): Promise<TemplateInfo[]> => {
  if (window.go?.main?.App?.GetTemplates) {
    return await window.go.main.App.GetTemplates()
  }
  return []
}
